name: CI

on:
  push:
    branches:
      - master

jobs:

  test:

    runs-on: macOS-latest

    name: Test library
    steps:
      - name: Use karma
        run: ng test AngularFavicon

  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build library
      run: ng build AngularFavicon
    - name: Try to publish
      run: |
        npm config set //registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN
        npm publish || true
        env:
          CI: true
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
